// <auto-generated />
namespace MMM.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsersRolesBankAccountsTransations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersRolesBankAccountsTransations));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241201298_Users-Roles-BankAccounts-Transations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
